### ISSUE TITLE
[Question]Why we need download pyspark?

### ISSUE THREAD

**Issue by doki23** [lakehq/sail#315]
```
(sail-venv) ➜  sail-venv pip3 install  "pysail[spark]==0.2.0.dev0"
Collecting pysail[spark]==0.2.0.dev0
  Using cached pysail-0.2.0.dev0-cp38-abi3-macosx_11_0_arm64.whl (26.8 MB)
Collecting pyspark[connect]<4.0,>=3.5
  Downloading pyspark-3.5.3.tar.gz (317.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 246.4/317.3 MB 1.9 MB/s eta 0:00:38
```
I think this package is a bit too large :(
Why we need download pyspark?

**Comment by linhr** [comment]
`pyspark` is a dependency of Sail so that the user can use the PySpark client to interact with the Sail server. `pyspark` is also required when the Sail server handles PySpark UDFs.

The large size of the `pyspark` package is due to the bundled Java/Scala libraries, which are not used by Sail. In the upcoming Spark 4.0 release, a separate Python-only package [`pyspark-connect`](https://pypi.org/project/pyspark-connect/) will be provided, which would greatly reduce the dependency size. We will replace `pyspark` with `pyspark-connect` to reduce the dependency footprint of Sail, when Spark 4.0 is ready.
